"""Train and save all fraud-detection models for both streams.

Reproduces the training done in notebooks/modeling.ipynb so the model
artifacts can be regenerated from a clean checkout:

    python scripts/train.py

The two datasets are treated as independent modeling problems with separate
pipelines (different feature structures). Small artifacts (Logistic Regression
models + scalers) are committed to the repo; the large Random Forests are
git-ignored and regenerated by running this script.

Inputs (produced by the EDA / feature-engineering notebooks, git-ignored):
  data/processed/X_train_fraud.csv, X_test_fraud.csv, y_train_fraud.csv,
      y_test_fraud.csv      -- already split, encoded, scaled and SMOTE-balanced
  data/processed/creditcard_cleaned.csv

Outputs (models/):
  logistic_regression_fraud.joblib, random_forest_fraud.joblib
  logistic_regression_creditcard.joblib, random_forest_creditcard.joblib,
      scaler_creditcard.joblib
"""
import os
import re

import joblib
import pandas as pd
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import average_precision_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

RANDOM_STATE = 42
PROCESSED = "data/processed"
MODELS = "models"


def _report(name, model, X_test, y_test):
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]
    auc_pr = average_precision_score(y_test, y_prob)
    f1 = f1_score(y_test, y_pred)
    print(f"  {name:28s} AUC-PR={auc_pr:.4f}  F1={f1:.4f}")


def _load_csv(path):
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Missing input '{path}'. Run the EDA/feature-engineering notebooks "
            f"first to populate data/processed/."
        )
    return pd.read_csv(path)


def train_ecommerce():
    """E-commerce stream — data is already split, encoded, scaled and SMOTE'd."""
    print("E-commerce stream (Fraud_Data.csv):")
    X_train = _load_csv(f"{PROCESSED}/X_train_fraud.csv")
    X_test = _load_csv(f"{PROCESSED}/X_test_fraud.csv")
    y_train = _load_csv(f"{PROCESSED}/y_train_fraud.csv").squeeze()
    y_test = _load_csv(f"{PROCESSED}/y_test_fraud.csv").squeeze()

    # get_dummies can produce column names with characters some libraries reject.
    clean = lambda df: df.rename(columns=lambda c: re.sub(r"[^\w]", "_", c))
    X_train, X_test = clean(X_train), clean(X_test)

    lr = LogisticRegression(max_iter=1000, random_state=RANDOM_STATE, n_jobs=-1)
    lr.fit(X_train, y_train)
    _report("Logistic Regression", lr, X_test, y_test)
    joblib.dump(lr, f"{MODELS}/logistic_regression_fraud.joblib")

    rf = RandomForestClassifier(
        n_estimators=300, max_depth=10, class_weight="balanced",
        random_state=RANDOM_STATE, n_jobs=-1,
    )
    rf.fit(X_train, y_train)
    _report("Random Forest", rf, X_test, y_test)
    joblib.dump(rf, f"{MODELS}/random_forest_fraud.joblib")


def train_creditcard():
    """Credit-card stream — full pipeline from the cleaned file."""
    print("Credit-card stream (creditcard.csv):")
    df = _load_csv(f"{PROCESSED}/creditcard_cleaned.csv")
    X, y = df.drop(columns=["Class"]), df["Class"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=RANDOM_STATE
    )

    scale_cols = ["Time", "Amount"]  # V1-V28 are already PCA-scaled
    scaler = StandardScaler()
    X_train = X_train.copy()
    X_test = X_test.copy()
    X_train[scale_cols] = scaler.fit_transform(X_train[scale_cols])
    X_test[scale_cols] = scaler.transform(X_test[scale_cols])
    joblib.dump(scaler, f"{MODELS}/scaler_creditcard.joblib")

    X_train_res, y_train_res = SMOTE(random_state=RANDOM_STATE).fit_resample(
        X_train, y_train
    )

    lr = LogisticRegression(max_iter=1000, random_state=RANDOM_STATE, n_jobs=-1)
    lr.fit(X_train_res, y_train_res)
    _report("Logistic Regression", lr, X_test, y_test)
    joblib.dump(lr, f"{MODELS}/logistic_regression_creditcard.joblib")

    rf = RandomForestClassifier(
        n_estimators=300, max_depth=10, class_weight="balanced",
        random_state=RANDOM_STATE, n_jobs=-1,
    )
    rf.fit(X_train_res, y_train_res)
    _report("Random Forest", rf, X_test, y_test)
    joblib.dump(rf, f"{MODELS}/random_forest_creditcard.joblib")


def main():
    os.makedirs(MODELS, exist_ok=True)
    train_ecommerce()
    train_creditcard()
    print(f"\nDone. Models written to {MODELS}/")


if __name__ == "__main__":
    main()
